### ISSUE TITLE
saying error as below

### ISSUE THREAD

**Issue by Aakash-DD** [AravindVasudev/Babble#2]
> babble@0.1.0 start C:\Users\AAKASH\Desktop\Follower-Github\Chat-app-all-F-2\Babble-master\Babble-master
> node ./bin/www

C:\Users\AAKASH\Desktop\Follower-Github\Chat-app-all-F-2\Babble-master\Babble-master\node_modules\passport-oauth2\lib\strategy.js:82
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
                           ^

TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (C:\Users\AAKASH\Desktop\Follower-Github\Chat-app-all-F-2\Babble-master\Babble-master\node_modules\passport-oauth2\lib\strategy.js:82:34)
    at new Strategy (C:\Users\AAKASH\Desktop\Follower-Github\Chat-app-all-F-2\Babble-master\Babble-master\node_modules\passport-facebook\lib\strategy.js:54:18)
    at Object.<anonymous> (C:\Users\AAKASH\Desktop\Follower-Github\Chat-app-all-F-2\Babble-master\Babble-master\config\passport.js:11:14)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\AAKASH\Desktop\Follower-Github\Chat-app-all-F-2\Babble-master\Babble-master\routes\index.js:9:14)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\AAKASH\Desktop\Follower-Github\Chat-app-all-F-2\Babble-master\Babble-master\app.js:23:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! babble@0.1.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the babble@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AAKASH\AppData\Roaming\npm-cache\_logs\2018-06-07T19_56_02_530Z-debug.log

**Comment by Aakash-DD** [comment]
plz help
